#!/usr/bin/env python3
"""DMR clean-protocol main table (gpt-5.5 judge, full 1173/task, stock reader).

Loads the judged per-arm files produced under the corrected protocol
(selector trained on aux_train_qa_pool; stock Qwen3-VL reader; retrieval = ColQwen2
top-16; evaluate on the full 1173 release test set per task). For each reader size and
task it reports per-arm means with bootstrap 95% CIs and the paired ablation
(naive→selector→assoc) vs the no-memory `pages` baseline and vs `naive`, plus the
genuine-prediction-change vs judge-noise split, retrieval stratification, and the
V-MQAR join-failure decomposition.

Pure analysis (no GPU). Reuses the stats core from dmr_analyze_results.py.
"""
from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

from dmr_analyze_results import (  # noqa: E402
    boot_ci, decompose_losses, fmt, load, mean_ci, paired, strat,
)

ARMS = ["pages", "naive", "selector", "assoc"]
ARM_LABEL = {
    "pages": "no-memory (retrieved pages only)",
    "naive": "+ lexical memory",
    "selector": "+ learned selector memory",
    "assoc": "+ associative memory (full DMR)",
}
TASKS = [("vmqar", "V-MQAR"), ("vniah", "V-NIAH")]


def _norm(s) -> str:
    return re.sub(r"\s+", " ", str(s or "").strip().lower())


def genuine_split(treat: dict, base: dict):
    """Split treat-vs-base judge delta into genuine (prediction text changed) vs
    judge-noise (identical prediction, score differs only from judge stochasticity)."""
    keys = sorted(set(treat) & set(base))
    gen_d = same_d = 0.0
    n_gen = n_same = 0
    for k in keys:
        if _norm(treat[k]["pred"]) == _norm(base[k]["pred"]):
            same_d += treat[k]["score"] - base[k]["score"]; n_same += 1
        else:
            gen_d += treat[k]["score"] - base[k]["score"]; n_gen += 1
    n = len(keys)
    return {"n": n, "n_genuine": n_gen, "n_same": n_same,
            "genuine_delta_per100": 100 * gen_d / n if n else float("nan"),
            "noise_delta_per100": 100 * same_d / n if n else float("nan")}


def full_recall_rate(arm: dict) -> float:
    vals = [1 for v in arm.values() if v.get("full_recall")]
    return len(vals) / len(arm) if arm else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sizes", default="2b,4b")
    ap.add_argument("--base", default="code/runs/20260630")
    ap.add_argument("--out", default="results/tables/dmr_clean_main_table.md")
    args = ap.parse_args()
    sizes = [s.strip() for s in args.sizes.split(",") if s.strip()]

    L: list[str] = []
    L.append("# DMR clean-protocol main results (gpt-5.5 judge)\n")
    L.append("> Selector trained on `aux_train_qa_pool` (PDF library, disjoint docs). Reader = "
             "**stock** Qwen3-VL (no fine-tuning). Retrieval = ColQwen2 top-16 (pretrained). "
             "Evaluated on the **full 1173 release test set** per task. Nothing in the pipeline "
             "trains on the 1173.\n")
    L.append("_Generated by scripts/dmr_clean_main_table.py; bootstrap CIs = 10k resamples._\n")

    for size in sizes:
        merged_judged = f"{args.base}/dmr_eval_{size}/judged"
        L.append(f"\n## Reader: stock Qwen3-VL-{size.upper()}-Instruct\n")
        loaded: dict[tuple[str, str], dict] = {}
        missing = False
        for task_key, _ in TASKS:
            for arm in ARMS:
                fp = f"{merged_judged}/{arm}_{task_key}.judged.jsonl"
                d = load(fp)
                loaded[(task_key, arm)] = d
                if not d:
                    missing = True
        if missing:
            L.append("_⚠️ one or more judged arm files missing/empty — partial._\n")

        # retrieval saturation note (from pages arm)
        L.append("**Retrieval full-recall@16 (gold pages present):** "
                 + ", ".join(
                     f"{disp} {fmt(full_recall_rate(loaded[(tk, 'pages')]))}"
                     for tk, disp in TASKS) + "\n")

        for task_key, disp in TASKS:
            L.append(f"\n### {disp} (n=1173)\n")
            L.append("| arm | judge | 95% CI | Δ vs pages | Δ vs naive | paired t (vs naive) | w/t/l vs naive |")
            L.append("|---|---|---|---|---|---|---|")
            pages = loaded[(task_key, "pages")]
            naive = loaded[(task_key, "naive")]
            for arm in ARMS:
                a = loaded[(task_key, arm)]
                if not a:
                    L.append(f"| {ARM_LABEL[arm]} | MISSING | — | — | — | — | — |"); continue
                m, lo, hi, n = mean_ci(a)
                dvp = paired(a, pages)["mean"] if pages else float("nan")
                if arm == "naive":
                    L.append(f"| {ARM_LABEL[arm]} | {fmt(m)} | [{fmt(lo)}, {fmt(hi)}] | "
                             f"{('+'+fmt(dvp)) if not math.isnan(dvp) else '—'} | — | — | — |")
                else:
                    pv = paired(a, naive) if naive else None
                    dvn = f"+{fmt(pv['mean'])}" if pv else "—"
                    tt = fmt(pv["t"], 2) if pv else "—"
                    wtl = f"{pv['win']}/{pv['tie']}/{pv['loss']}" if pv else "—"
                    L.append(f"| {ARM_LABEL[arm]} | {fmt(m)} | [{fmt(lo)}, {fmt(hi)}] | "
                             f"{('+'+fmt(dvp)) if not math.isnan(dvp) else '—'} | {dvn} | {tt} | {wtl} |")

            # headline full DMR vs pages, with genuine-vs-noise + stratification
            assoc = loaded[(task_key, "assoc")]
            if assoc and pages:
                ph = paired(assoc, pages)
                gs = genuine_split(assoc, pages)
                L.append(f"\n**Full DMR vs no-memory baseline:** Δ=+{fmt(ph['mean'])} "
                         f"(95% CI [{fmt(ph['ci'][0])}, {fmt(ph['ci'][1])}], t={fmt(ph['t'],2)}, "
                         f"w/t/l {ph['win']}/{ph['tie']}/{ph['loss']}). "
                         f"Genuine prediction-change Δ={fmt(gs['genuine_delta_per100'],1)}/100 "
                         f"over {gs['n_genuine']} changed; judge-noise floor "
                         f"{fmt(gs['noise_delta_per100'],1)}/100 over {gs['n_same']} identical.")
            if assoc and naive:
                st = strat(assoc, naive)
                rs = st.get("recall_success"); rm = st.get("recall_miss")
                seg = []
                if rs:
                    seg.append(f"recall-hit n={rs['n']}: {fmt(rs['naive'])}→{fmt(rs['treat'])} (Δ+{fmt(rs['diff'])})")
                if rm:
                    seg.append(f"recall-miss n={rm['n']}: {fmt(rm['naive'])}→{fmt(rm['treat'])} (Δ+{fmt(rm['diff'])})")
                if seg:
                    L.append("\n**Stratified (full DMR vs naive, by retrieval full-recall):** " + "; ".join(seg) + ".")

            # V-MQAR join-failure decomposition on the selector arm
            if task_key == "vmqar":
                sel = loaded[(task_key, "selector")]
                if sel:
                    dec = decompose_losses(sel)
                    tot = sum(dec.values())
                    L.append(f"\n**V-MQAR selector-arm loss decomposition (non-correct n={tot}):** "
                             f"reader cross-page JOIN={dec['join_failure']}, "
                             f"retrieval miss={dec['retrieval_miss']}, "
                             f"selector dropped gold block={dec['selector_dropped']}, "
                             f"other={dec['other']}.")
            L.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\n-> wrote {out}")


if __name__ == "__main__":
    main()
